#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi
echo "setting up assets."
ln run.sh gobbler
cp -r . ~/.Gobbler
chmod +x gobbler
mv gobbler /bin/gobbler
echo "Setup complete, please ensure that you have read the README.md for Usage."
